# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NnLqLVc7lfpNUz1d5NF0Q3GgyROFoNQ1
"""

with open("requirements.txt", "w") as f:
    f.write("streamlit\nnumpy\nscipy\nmatplotlib")

from google.colab import files
files.download("requirements.txt")