# -*- coding: utf-8 -*-
"""simulator_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yDa5NFWv5EMGLMEH_1_9XYBWB-p3FB_0
"""

code = '''
import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

def nutrient_growth(T, t, r, K0, Km, N):
    K = K0 * (N / (N + Km))
    dTdt = r * T * (1 - T / K)
    return dTdt

st.title("🧬 Tissue Growth Simulator")

r = st.slider("Growth rate (r)", 0.1, 1.0, 0.3, 0.01)
T0 = st.slider("Initial cell density", 1, 100, 10, 1)
N0 = st.slider("Nutrient concentration", 1, 100, 50, 1)
K0 = st.slider("Max carrying capacity", 100, 1000, 500, 50)
Km = st.slider("Nutrient constant", 1, 100, 10, 1)
time_max = st.slider("Simulation time", 10, 200, 50, 5)

t = np.linspace(0, time_max, 200)
T = odeint(nutrient_growth, T0, t, args=(r, K0, Km, N0)).flatten()

fig, ax = plt.subplots()
ax.plot(t, T)
ax.set_xlabel("Time (days)")
ax.set_ylabel("Tissue Mass")
ax.set_title("Tissue Growth Over Time")
st.pyplot(fig)
'''

with open("simulator_app.py", "w") as f:
    f.write(code)